[package]
name = "cairo-lang-eq-solver"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Equation solving for Sierra generation."

[dependencies]
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.1.0-rc0" }
good_lp.workspace = true
indexmap = { workspace = true, features = ["std"] }
itertools = { workspace = true, features = ["use_std"] }

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
test-case.workspace = true
test-log.workspace = true
